server:
  port: 8888

spring:
  # DATA SOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/small?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: qiong
    driver-class-name: com.mysql.cj.jdbc.Driver


media:
  # 媒体储存
  save:
    path: D:\WAREHOUSE\SAVE
  access:
    path: static