server:
  port: 8889

spring:
  # DATA SOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/prod?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: qiong
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    # password: yourpassword  # 如果没有密码可以省略
    database: 0            # 默认使用0号数据库
    lettuce:
      pool:
        max-active: 8      # 连接池最大连接数
        max-idle: 8        # 连接池最大空闲连接数
        min-idle: 0        # 连接池最小空闲连接数
        max-wait: -1ms     # 连接池最大阻塞等待时间(负值表示没有限制)
    timeout: 5000ms        # 连接超时时间

media:
  # 媒体储存
  save:
    path: D:\WAREHOUSE\SAVE
  access:
    path: static
